[package]
name = "pokedex"
description = "Ari's first CLI in Rust"
version = "0.1.4"
authors = ["Ari Vaniderstine <ari.vaniderstine@embark-studios.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.9.22"
serde_json = "1.0"
clap = "2"
console = "0.9"
serde = { version = "1.0", features = ["derive"] }
